[package]
name = "stock_market_monitor_proj_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yahoo_finance_api = "2.1.0"
plotters = "0.3"
clap = "4.5.0"